### ISSUE TITLE
setup.py is missing

### ISSUE THREAD

**Issue by sobolevn** [lk-geimfari/kolkrabba#4]
There's no habitual way to install your package. 
Would you mind to create it and proper docs?

Maybe it is also convenient to `pypi`?

**Comment by lk-geimfari** [comment]
@sobolevn Yes, of course I wanna add this package in PyPi, but the code is still not perfect and i have bugs in code. Also i gonna add more information and  documentation. I'll work on it. Thank you for issues!

**Comment by lk-geimfari** [comment]
I'll work to eliminate imperfections.

**Comment by lk-geimfari** [comment]
I submitted package to PyPi, but i have some issues with modules. The kolkrabba's modules does not imported when use `pip install kolkrabba`, but on local (python setup.py install) all worked.

**Comment by sobolevn** [comment]
Well, it does work for me.

> (kolkrabba) [3:04:49] sobolev :: MacBook-Pro-Nikita  ➜  Documents/github/git-secret ‹develop› » ls /Users/sobolev/.virtualenvs/kolkrabba/lib/python2.7/site-packages/kolkrabba/
> __init__.py    kolkrabba.py   messages.py    useriniter.py
> __init__.pyc   kolkrabba.pyc  messages.pyc   useriniter.pyc
> (kolkrabba) [3:05:03] sobolev :: MacBook-Pro-Nikita  ➜  Documents/github/git-secret ‹develop› » python
> Python 2.7.11 (default, Dec 26 2015, 17:47:53) 
> [GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)] on darwin
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import kolkrabba

**Comment by lk-geimfari** [comment]
On Python 2.7 all worked, but does not work on Python 3.x
