### ISSUE TITLE
limit to python 3.4 is too strict

### ISSUE THREAD

**Issue by sobolevn** [lk-geimfari/kolkrabba#5]
Are there any reasons doing so?

**Comment by lk-geimfari** [comment]
@sobolevn Until last update all worked and with Python 2.x, but in the process the code is not compatible. I wanna fix it.

**Comment by lk-geimfari** [comment]
Backward compatibility is restored. Now all worked on Python 2.x/Python 3.x

**Comment by sobolevn** [comment]
Ready to close?

**Comment by lk-geimfari** [comment]
@sobolevn Yes
